name: IRCTC Automation Booking

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      USERNAME:
        required: true
        type: string
      PASSWORD:
        required: true
        type: string

jobs:
  IRCTC-Booking:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies
    - run: |
        pip install -r irctc-captcha-solver/requirements.txt
        if [ -z "${{ env.USERNAME }}" ]; then
          USERNAME="${{ secrets.USERNAME }}"
        else
          USERNAME="${{ env.USERNAME }}"
        fi
        if [ -z "${{ env.PASSWORD }}" ]; then
          PASSWORD="${{ secrets.PASSWORD }}"
        else
          PASSWORD="${{ env.PASSWORD }}"
        fi
        echo ::add-mask::$PASSWORD
        echo ::add-mask::$USERNAME
        echo PASSWORD=$PASSWORD >> $GITHUB_ENV
        echo USERNAME=$USERNAME >> $GITHUB_ENV

    # python3 irctc-captcha-solver/app.py "" is used for models to load before starting tatkal tickets 

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '21.7.1'

    - name: Running IRCTC Cypress Script
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        command: npx cypress run --record --key a15b31a6-b9ee-4678-b9ac-f45a190851fe --browser chrome --env USERNAME=${{ env.USERNAME }},PASSWORD=${{ env.PASSWORD }}
